// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAutenticacao.Data;

namespace SistemaAutenticacao.Migrations
{
    [DbContext(typeof(SistemaAutenticacaoContext))]
    [Migration("20191122182018_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaAutenticacao.Models.AreaCientifica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoordenadorIDID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDepartamentoID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecretarioIDID")
                        .HasColumnType("int");

                    b.Property<int?>("SubCoordenadorIDID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CoordenadorIDID");

                    b.HasIndex("IdDepartamentoID");

                    b.HasIndex("SecretarioIDID");

                    b.HasIndex("SubCoordenadorIDID");

                    b.ToTable("AreaCientifica");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.Curso", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEscolaID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IdEscolaID");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.Departamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CoordenadorIDID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEscolaID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecretarioIDID")
                        .HasColumnType("int");

                    b.Property<int?>("SubCoordenadorIDID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CoordenadorIDID");

                    b.HasIndex("IdEscolaID");

                    b.HasIndex("SecretarioIDID");

                    b.HasIndex("SubCoordenadorIDID");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.Escola", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abreviatura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Nif")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Escola");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTipoUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Nif")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.AreaCientifica", b =>
                {
                    b.HasOne("SistemaAutenticacao.Models.User", "CoordenadorID")
                        .WithMany()
                        .HasForeignKey("CoordenadorIDID");

                    b.HasOne("SistemaAutenticacao.Models.Departamento", "IdDepartamento")
                        .WithMany("AreaCientifica")
                        .HasForeignKey("IdDepartamentoID");

                    b.HasOne("SistemaAutenticacao.Models.User", "SecretarioID")
                        .WithMany()
                        .HasForeignKey("SecretarioIDID");

                    b.HasOne("SistemaAutenticacao.Models.User", "SubCoordenadorID")
                        .WithMany()
                        .HasForeignKey("SubCoordenadorIDID");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.Curso", b =>
                {
                    b.HasOne("SistemaAutenticacao.Models.Escola", "IdEscola")
                        .WithMany()
                        .HasForeignKey("IdEscolaID");
                });

            modelBuilder.Entity("SistemaAutenticacao.Models.Departamento", b =>
                {
                    b.HasOne("SistemaAutenticacao.Models.User", "CoordenadorID")
                        .WithMany()
                        .HasForeignKey("CoordenadorIDID");

                    b.HasOne("SistemaAutenticacao.Models.Escola", "IdEscola")
                        .WithMany("Departamento")
                        .HasForeignKey("IdEscolaID");

                    b.HasOne("SistemaAutenticacao.Models.User", "SecretarioID")
                        .WithMany()
                        .HasForeignKey("SecretarioIDID");

                    b.HasOne("SistemaAutenticacao.Models.User", "SubCoordenadorID")
                        .WithMany()
                        .HasForeignKey("SubCoordenadorIDID");
                });
#pragma warning restore 612, 618
        }
    }
}
